name: Tests

on: [push]

jobs:
  tests:
    name: ubuntu-latest / ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v5

    - name: Install uv and set Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Build solution
      run: |
        uv build

    - name: Run yapf
      run: |
        uv run yapf --diff --recursive ruuvigate

    - name: Run mypy
      run: |
        uv run mypy .

    - name: Run pytest
      run: |
        uv run pytest
